#!/usr/bin/env bash
# iamlazy uninstaller — removes only files that carry the `iamlazy-managed`
# marker. Never touches ~/.iamlazy/runs.jsonl and never touches any PROJECT.md.
set -eu

MARKER="iamlazy-managed"

TARGETS="\
${HOME}/.claude/commands/iamlazy.md \
${HOME}/.claude/commands/iamlazy-review.md \
${HOME}/.claude/agents/iamlazy-critic.md \
${HOME}/.config/opencode/commands/iamlazy.md \
${HOME}/.config/opencode/commands/iamlazy-review.md \
${HOME}/.config/opencode/agents/iamlazy.md \
${HOME}/.config/opencode/agents/iamlazy-critic.md"

remove_if_managed() {
  f="$1"
  if [ ! -f "$f" ]; then
    return 0
  fi
  if grep -q "$MARKER" "$f" 2>/dev/null; then
    rm -f "$f"
    echo "  removed $f"
  else
    echo "  SKIP (not $MARKER): $f" >&2
  fi
}

echo "iamlazy uninstaller"
for t in $TARGETS; do
  remove_if_managed "$t"
done

# Layer 0 hooks live in their own directory and are generated wholesale by
# --with-hooks, so the directory itself is the marker. settings.json is NEVER
# touched: the installer did not write it, so the uninstaller does not get to
# edit it either -- the human pasted that block and the human removes it.
# Layer 0: unregister first (while the merge script still exists), then remove.
# Only entries pointing at our hook dir are dropped -- the user's own hooks and
# every other setting are left exactly as they were.
if [ -d "${HOME}/.claude/iamlazy-hooks" ]; then
  if [ -x "${HOME}/.claude/iamlazy-hooks/merge-settings.sh" ]; then
    "${HOME}/.claude/iamlazy-hooks/merge-settings.sh" \
      "${HOME}/.claude/settings.json" "${HOME}/.claude/iamlazy-hooks" --remove \
      || echo "  NOTE: could not edit settings.json; remove the iamlazy hooks block by hand." >&2
  fi
  rm -rf "${HOME}/.claude/iamlazy-hooks"
  echo "  removed ${HOME}/.claude/iamlazy-hooks/ (Layer 0 scripts)"
fi

# The DELTAS mirror is generated by the installer, not user data, and carries no marker.
# Remove it explicitly -- and only it; runs.jsonl stays.
if [ -f "${HOME}/.iamlazy/DELTAS.md" ]; then
  rm -f "${HOME}/.iamlazy/DELTAS.md"
  echo "  removed ${HOME}/.iamlazy/DELTAS.md (generated mirror)"
fi

echo
echo "done. Your data was left untouched:"
echo "  ~/.iamlazy/runs.jsonl  (run log)"
echo "  ~/.iamlazy/prices.conf (your price table)"
echo "  any PROJECT.md         (project ground truth)"
