#!/usr/bin/env bash
# iamlazy uninstaller — removes only files that carry the `iamlazy-managed`
# marker. Never touches ~/.iamlazy/runs.jsonl and never touches any PROJECT.md.
set -eu

MARKER="iamlazy-managed"

TARGETS="\
${HOME}/.claude/commands/iamlazy.md \
${HOME}/.claude/commands/iamlazy-review.md \
${HOME}/.claude/agents/iamlazy-critic.md \
${HOME}/.config/opencode/commands/iamlazy.md \
${HOME}/.config/opencode/commands/iamlazy-review.md \
${HOME}/.config/opencode/agents/iamlazy.md \
${HOME}/.config/opencode/agents/iamlazy-critic.md"

remove_if_managed() {
  f="$1"
  if [ ! -f "$f" ]; then
    return 0
  fi
  if grep -q "$MARKER" "$f" 2>/dev/null; then
    rm -f "$f"
    echo "  removed $f"
  else
    echo "  SKIP (not $MARKER): $f" >&2
  fi
}

echo "iamlazy uninstaller"
for t in $TARGETS; do
  remove_if_managed "$t"
done

# Layer 0 hooks live in their own directory and are generated wholesale by
# --with-hooks, so the directory itself is the marker. settings.json is NEVER
# touched: the installer did not write it, so the uninstaller does not get to
# edit it either -- the human pasted that block and the human removes it.
if [ -d "${HOME}/.claude/iamlazy-hooks" ]; then
  rm -rf "${HOME}/.claude/iamlazy-hooks"
  echo "  removed ${HOME}/.claude/iamlazy-hooks/ (Layer 0 scripts)"
  echo "  NOTE: remove the iamlazy \"hooks\" block from your settings.json by hand." >&2
fi

# The DELTAS mirror is generated by the installer, not user data, and carries no marker.
# Remove it explicitly -- and only it; runs.jsonl stays.
if [ -f "${HOME}/.iamlazy/DELTAS.md" ]; then
  rm -f "${HOME}/.iamlazy/DELTAS.md"
  echo "  removed ${HOME}/.iamlazy/DELTAS.md (generated mirror)"
fi

echo
echo "done. Your data was left untouched:"
echo "  ~/.iamlazy/runs.jsonl  (run log)"
echo "  any PROJECT.md         (project ground truth)"
