#!/usr/bin/env bash
# iamlazy uninstaller — removes only files that carry the `iamlazy-managed`
# marker. Never touches ~/.iamlazy/runs.jsonl and never touches any PROJECT.md.
set -eu

MARKER="iamlazy-managed"

TARGETS="\
${HOME}/.claude/skills/iamlazy/SKILL.md \
${HOME}/.claude/skills/iamlazy-review/SKILL.md \
${HOME}/.claude/commands/iamlazy.md \
${HOME}/.claude/commands/iamlazy-review.md \
${HOME}/.claude/agents/iamlazy-critic.md \
${HOME}/.config/opencode/commands/iamlazy.md \
${HOME}/.config/opencode/commands/iamlazy-review.md \
${HOME}/.config/opencode/agents/iamlazy.md \
${HOME}/.config/opencode/agents/iamlazy-critic.md \
${HOME}/.config/opencode/plugins/iamlazy.ts \
${HOME}/.config/opencode/plugins/iamlazy.js"

remove_if_managed() {
  f="$1"
  if [ ! -f "$f" ]; then
    return 0
  fi
  if grep -q "$MARKER" "$f" 2>/dev/null; then
    rm -f "$f"
    echo "  elimine $f"
  else
    echo "  SALTEADO (no es $MARKER): $f" >&2
  fi
}

echo "desinstalador de iamlazy"
for t in $TARGETS; do
  remove_if_managed "$t"
done
# A skill is a folder; it goes with its SKILL.md, and only when nothing else of
# the human's is left inside it.
for d in "${HOME}/.claude/skills/iamlazy" "${HOME}/.claude/skills/iamlazy-review"; do
  if [ -d "$d" ] && rmdir "$d" 2>/dev/null; then echo "  elimine $d/"; fi
done

# Layer 0 hooks live in their own directory and are generated wholesale by
# --with-hooks, so the directory itself is the marker. settings.json is NEVER
# touched: the installer did not write it, so the uninstaller does not get to
# edit it either -- the human pasted that block and the human removes it.
# Layer 0: unregister first (while the merge script still exists), then remove.
# Only entries pointing at our hook dir are dropped -- the user's own hooks and
# every other setting are left exactly as they were.
if [ -d "${HOME}/.claude/iamlazy-hooks" ]; then
  if [ -x "${HOME}/.claude/iamlazy-hooks/merge-settings.sh" ]; then
    "${HOME}/.claude/iamlazy-hooks/merge-settings.sh" \
      "${HOME}/.claude/settings.json" "${HOME}/.claude/iamlazy-hooks" --remove \
      || echo "  NOTA: no pude editar settings.json; quita el bloque de hooks de iamlazy a mano." >&2
  fi
  rm -rf "${HOME}/.claude/iamlazy-hooks"
  echo "  elimine ${HOME}/.claude/iamlazy-hooks/ (scripts de Layer 0)"
fi

# The OpenCode copy of the same scripts. The plugin that invoked them was
# removed above, by marker, with the other generated files.
if [ -d "${HOME}/.config/opencode/iamlazy-hooks" ]; then
  rm -rf "${HOME}/.config/opencode/iamlazy-hooks"
  echo "  elimine ${HOME}/.config/opencode/iamlazy-hooks/ (scripts de Layer 0 para el plugin de OpenCode)"
fi

# The DELTAS mirror and the hooks_version stamp are both generated by the
# installer, not user data, and carry no marker. Removed explicitly -- and
# only them; runs.jsonl stays. Leaving hooks_version behind would claim a
# version is installed after the hooks it names are gone.
if [ -f "${HOME}/.iamlazy/DELTAS.md" ]; then
  rm -f "${HOME}/.iamlazy/DELTAS.md"
  echo "  elimine ${HOME}/.iamlazy/DELTAS.md (espejo generado)"
fi
if [ -f "${HOME}/.iamlazy/hooks_version" ]; then
  rm -f "${HOME}/.iamlazy/hooks_version"
  echo "  elimine ${HOME}/.iamlazy/hooks_version (marca generada)"
fi

echo
echo "listo. Tus datos quedaron intactos:"
echo "  ~/.iamlazy/runs.jsonl  (log de corridas)"
echo "  ~/.iamlazy/prices.conf (tu tabla de precios)"
echo "  cualquier PROJECT.md   (verdad del proyecto)"
